import { Task, User } from '@/types';

export const mockUsers: User[] = [
    {
        id: '1',
        name: 'Priya Sharma',
        email: 'priya.sharma@example.com',
        avatar: '/api/placeholder/40/40',
        rating: 4.9,
        reviewCount: 127,
        skills: ['Web Design', 'UI/UX', 'Figma'],
        joinedDate: '2023-01-15',
        completedTasks: 89,
        isVerified: true,
    },
    {
        id: '2',
        name: 'Rajesh Thapa',
        email: 'rajesh.thapa@example.com',
        avatar: '/api/placeholder/40/40',
        rating: 4.7,
        reviewCount: 93,
        skills: ['React', 'Node.js', 'TypeScript'],
        joinedDate: '2023-03-20',
        completedTasks: 65,
        isVerified: true,
    },
    {
        id: '3',
        name: 'Sita Poudel',
        email: 'sita.poudel@example.com',
        avatar: '/api/placeholder/40/40',
        rating: 4.8,
        reviewCount: 156,
        skills: ['Content Writing', 'SEO', 'Marketing'],
        joinedDate: '2022-11-10',
        completedTasks: 112,
        isVerified: true,
    },
    {
        id: '4',
        name: 'Arjun Gurung',
        email: 'arjun.gurung@example.com',
        avatar: '/api/placeholder/40/40',
        rating: 4.6,
        reviewCount: 78,
        skills: ['Graphic Design', 'Logo Design', 'Branding'],
        joinedDate: '2023-05-05',
        completedTasks: 54,
        isVerified: false,
    },
    {
        id: '5',
        name: 'Sujan Maharjan',
        email: 'sujan.maharjan@example.com',
        avatar: '/api/placeholder/40/40',
        rating: 4.8,
        reviewCount: 89,
        skills: ['Full Stack Development', 'Next.js', 'MongoDB'],
        joinedDate: '2023-02-10',
        completedTasks: 67,
        isVerified: true,
    },
    {
        id: '6',
        name: 'Kamala Shrestha',
        email: 'kamala.shrestha@example.com',
        avatar: '/api/placeholder/40/40',
        rating: 4.7,
        reviewCount: 134,
        skills: ['Digital Marketing', 'Social Media', 'Content Strategy'],
        joinedDate: '2022-12-05',
        completedTasks: 98,
        isVerified: true,
    },
    {
        id: '7',
        name: 'Dipak Tamang',
        email: 'dipak.tamang@example.com',
        avatar: '/api/placeholder/40/40',
        rating: 4.9,
        reviewCount: 76,
        skills: ['Video Editing', 'Motion Graphics', 'Animation'],
        joinedDate: '2023-04-18',
        completedTasks: 45,
        isVerified: true,
    },
    {
        id: '8',
        name: 'Sunita Rai',
        email: 'sunita.rai@example.com',
        avatar: '/api/placeholder/40/40',
        rating: 4.6,
        reviewCount: 112,
        skills: ['Data Entry', 'Excel', 'Virtual Assistant'],
        joinedDate: '2023-01-30',
        completedTasks: 156,
        isVerified: false,
    },
];

export const mockTasks: Task[] = [
    {
        id: '1',
        title: 'Design a Modern Logo for Tech Startup',
        description: 'I need a professional, modern logo for my AI technology startup. The logo should be minimalist, scalable, and work well in both color and monochrome versions. Please include 3 different concepts with source files.',
        category: 'Design',
        budget: { min: 19500, max: 39000 },
        deadline: '2024-11-15',
        skillsRequired: ['Logo Design', 'Graphic Design', 'Adobe Illustrator'],
        difficulty: 'Medium',
        status: 'Open',
        clientId: '1',
        client: mockUsers[0],
        proposals: [],
        createdAt: '2024-10-01',
        updatedAt: '2024-10-01',
        tags: ['logo', 'design', 'startup', 'tech'],
        attachments: [],
    },
    {
        id: '2',
        title: 'Build a React Dashboard Component',
        description: 'Need a responsive dashboard component built in React with TypeScript. Should include charts, data tables, and filtering capabilities. Must be mobile-friendly and follow modern design principles.',
        category: 'Development',
        budget: { min: 52000, max: 104000 },
        deadline: '2024-11-20',
        skillsRequired: ['React', 'TypeScript', 'Tailwind CSS'],
        difficulty: 'Hard',
        status: 'Open',
        clientId: '2',
        client: mockUsers[1],
        proposals: [],
        createdAt: '2024-10-02',
        updatedAt: '2024-10-02',
        tags: ['react', 'dashboard', 'typescript', 'frontend'],
    },
    {
        id: '3',
        title: 'Write SEO-Optimized Blog Posts',
        description: 'Looking for a content writer to create 5 SEO-optimized blog posts about digital marketing trends. Each post should be 1500-2000 words with proper keyword integration and engaging content.',
        category: 'Writing',
        budget: { min: 26000, max: 52000 },
        deadline: '2024-11-25',
        skillsRequired: ['Content Writing', 'SEO', 'Digital Marketing'],
        difficulty: 'Medium',
        status: 'In Progress',
        clientId: '3',
        client: mockUsers[2],
        proposals: [],
        createdAt: '2024-09-28',
        updatedAt: '2024-10-05',
        tags: ['content', 'seo', 'blog', 'marketing'],
    },
    {
        id: '4',
        title: 'Create Social Media Graphics Package',
        description: 'Need a complete social media graphics package including Instagram posts, stories, and Facebook cover images. Should follow brand guidelines and be provided in various formats.',
        category: 'Design',
        budget: { min: 13000, max: 32500 },
        deadline: '2024-11-10',
        skillsRequired: ['Graphic Design', 'Social Media Design', 'Canva'],
        difficulty: 'Easy',
        status: 'Open',
        clientId: '4',
        client: mockUsers[3],
        proposals: [],
        createdAt: '2024-10-03',
        updatedAt: '2024-10-03',
        tags: ['social media', 'graphics', 'instagram', 'facebook'],
    },
    {
        id: '5',
        title: 'Mobile App UI/UX Design',
        description: 'Design a complete UI/UX for a fitness tracking mobile app. Need wireframes, user flow, and high-fidelity mockups for both iOS and Android. Should include onboarding, main dashboard, and workout tracking screens.',
        category: 'Design',
        budget: { min: 78000, max: 156000 },
        deadline: '2024-12-01',
        skillsRequired: ['UI/UX Design', 'Figma', 'Mobile Design'],
        difficulty: 'Hard',
        status: 'Open',
        clientId: '1',
        client: mockUsers[0],
        proposals: [],
        createdAt: '2024-10-04',
        updatedAt: '2024-10-04',
        tags: ['mobile', 'ui', 'ux', 'app', 'fitness'],
    },
    {
        id: '6',
        title: 'Setup WordPress E-commerce Site',
        description: 'Need help setting up a WordPress e-commerce website using WooCommerce. Includes theme customization, payment gateway integration, and basic SEO setup.',
        category: 'Development',
        budget: { min: 39000, max: 78000 },
        deadline: '2024-11-18',
        skillsRequired: ['WordPress', 'WooCommerce', 'PHP'],
        difficulty: 'Medium',
        status: 'Open',
        clientId: '2',
        client: mockUsers[1],
        proposals: [],
        createdAt: '2024-10-05',
        updatedAt: '2024-10-05',
        tags: ['wordpress', 'ecommerce', 'woocommerce', 'website'],
    },
];

export const categories = [
    'All Categories',
    'Development',
    'Design',
    'Writing',
    'Marketing',
    'Data Entry',
    'Virtual Assistant',
    'Translation',
    'Video & Animation',
    'Music & Audio',
];